id: 78f994b3-81c3-446f-a237-a7aed11ce883
name: ProjectContext
type: c4-project
description: This is a sample project configuration for C4 model generation.
children:
- id: a0aabaf7-ca5c-4bce-9ceb-30c195310d30
  type: software-system
- id: 6bf36d02-6a3b-45e3-92c2-d20e75449a15
  type: person
tenantId: 5f37364f-201e-47ea-2e89-08dd02619fda
